services:
  ftp-server:
    image: garethflowers/ftp-server
    container_name: my-ftp-server
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - './data:/home/user'
