---
name: Check for forbidden licenses

# Checks for any forbidden/copyleft licenses using their SPDX identifiers
# (https://spdx.org/licenses/)

# List of copyleft licenses derived from Blue Oak Council Guide to Copyleft
# https://blueoakcouncil.org/copyleft

# List of forbidden licenses derived from Google License Classifier
# (https://github.com/google/licenseclassifier)

on:
  pull_request:
    branches:
      - trunk
      - release-*

jobs:
  license-check:
    name: license check
    runs-on: ubuntu-latest
    env:
      FORBIDDEN_LICENSE_CHECK: |
        grep -E "GPL|CC|APSL|CPAL|EUPL|NPOSL|OSL|SSPL|Parity|RPL|QPL|Sleepycat|copyleft|CDDL|CPL|EPL|ErlPL|IPL|MPL|MS-RL|SPL|WTFPL|Facebook|Commons-Clause" | grep . && exit 1 || echo "ok" 
    steps:
      - uses: actions/checkout@v2

      - name: Install trader packages
        working-directory: trader
        run: |
          npm install

      - name: Check trader package licenses
        working-directory: trader
        run: |
          npx license-checker |& ${{ env.FORBIDDEN_LICENSE_CHECK }}
